DeviceLog/Controllers/DeviceStatusController.cs
using System.IO;
using System.Linq;
using Newtonsoft.Json;
using Inventory.Models;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.Controllers
{
    public class DeviceStatusController : Controller
    {
        [HttpGet]
        public IActionResult Index(string team = null, string serialNumber = null)
        {
            var Data = new DeviceStatusUpdate();
            try
            {
                team = team.Replace("+", " ");
                Data.TeamName = team;
            }
            catch
            {
                Data.Error = "Team name can't be empty";
                return View(Data);
            }
            //string line;
            Data.Devices = Directory.GetFiles("./Data/" + team).ToList();
            for (var i = 0; i < Data.Devices.Count(); i++)
            {
                Data.Devices[i] = Data.Devices[i].Replace("./Data/" + team + "\\", "").Replace(".txt", "");
            }
            Data.Teams = Directory.GetDirectories("./Data/").ToList();
            for (var j = 0; j < Data.Teams.Count(); j++)
            {
                Data.Teams[j] = Data.Teams[j].Replace("./Data/", "");
            }
            if (!string.IsNullOrEmpty(serialNumber))
            {
                Data.SerialNumber = serialNumber;
                try
                {
                    var deviceFile = new StreamReader("./Data/" + team + "/" + serialNumber + ".txt");
                    Data.Device = new DeviceDetails();
                    var deviceDetails = deviceFile.ReadToEnd();
                    Data.Device = JsonConvert.DeserializeObject<DeviceDetails>(deviceDetails);
                    deviceFile.Close();
                }
                catch
                {
                    Data.Error = "Device info not found";
                }
            }
            return View(Data);
        }
        [HttpGet]
        public IActionResult StatusUpdate(DeviceDetails details)
        {
            var output = new DeviceStatusUpdate();
            output.Device = details;
            try
            {
                if(details.LoanStatus == null)
                {
                    details.LoanStatus = "false";
                    details.LoanedTeam = "";
                }
                var data = JsonConvert.SerializeObject(details);
                var path = "./Data/" + details.OwnerTeam.Replace("+", " ") + "/" + details.DeviceName + ".txt";
                if (!System.IO.File.Exists(path))
                {
                    using (StreamWriter sw = System.IO.File.CreateText(path))
                    {
                        sw.WriteLine(data);
                    }
                }
                else
                {
                    System.IO.File.WriteAllText(path, data);
                }
                return View(output);
            }
            catch
            {
                output.Error = "There was some error while updating the device status, please try again later.";
                return View(output);
            }
        }
    }
}

DeviceLog/Controllers/HomeController.cs
using DeviceLog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace DeviceLog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var Teams = Directory.GetDirectories("./Data/");
            for (var i = 0; i < Teams.Count(); i++)
            {
                Teams[i] = Teams[i].Replace("./Data/", "");
            }
            return View(Teams);
        }
    }
}

DeviceLog/Views/Home/Index.cshtml
@model string[];
@{
    ViewData["Title"] = "Status Update";
}
<h4 class="mb-3">Select your Team: </h4>
<form method="get" asp-controller="DeviceStatus" asp-action="Index">
    <div class="form-group">
        <div class="input-group mb-3">
            <select class="custom-select" id="Team" onclick="TeamSelect()">
                <option selected>Select your team</option>
                @foreach (var id in Model)
                {
                    <option value="@id">@id</option>
                }
            </select>
        </div>
    </div>
    <input type="hidden" name="team" id="teamSubmit" value="" />
    <button type="submit" class="btn btn-primary" id="submitBtn" onclick="onSubmit()" disabled>Submit</button>
</form>
<script type="text/javascript">
    function TeamSelect() {
        if (document.getElementById('Team').selectedIndex !== 0) {
            document.getElementById("submitBtn").removeAttribute("disabled");
        } else {
            document.getElementById("submitBtn").setAttribute("disabled", "true");
        }
    }
    function onSubmit() {
        document.getElementById("teamSubmit").value = document.getElementById('Team').selectedOptions[0].value;        
    }
</script>